### ISSUE TITLE
Library versions undocumented

### ISSUE THREAD

**Issue by haberdashPI** [GuanLab/DeepSleep#1]
Thanks for writing such a solid paper, and sharing your model code. 

I was just wondering: do you have the actual versions of the libraries you used to run this? There is no file in the repo storing this information, that I can find, so it is actually quite hard to get the code in this repository running.

**Comment by Hongyang449** [comment]
Hi,

I've listed the versions in the README.md file:

python (3.6.5) 
numpy (1.13.3). 
scikit-learn (0.19.0)
tensorflow (1.8.0) 
keras (2.0.4)

Thanks!

**Comment by haberdashPI** [comment]
Thank you kindly!!
