### ISSUE TITLE
uniform_8m.py not working on Windows

### ISSUE THREAD

**Issue by Armina1506** [GuanLab/DeepSleep#2]
The command `python uniform_8m.py` does not work on Windows.
To make it more platform-independent change the lines 29 and 30 to:
```
os.mkdir(path2)
os.mkdir(path3)
```

**Comment by Hongyang449** [comment]
Thank you for your suggestion! I've updated it.

**Comment by saifsal** [comment]
If the folders already exist you get the following error:
```
FileExistsError: [Errno 17] File exists: './data/feature_8m/'
```
I have solved it by modifying the lines further:
```
os.makedirs(path2, exist_ok=True)
os.makedirs(path3, exist_ok=True)
```
I have tested this on both Windows and Linux.

**Comment by Hongyang449** [comment]
Good catch! I've updated it.
