### ISSUE TITLE
Citation of this repository

### ISSUE THREAD

**Issue by Armina1506** [GuanLab/DeepSleep#3]
Is it possible for you to make the repository citable, so we can use it for our research? It would be very helpful of you. :)

https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository

**Comment by Hongyang449** [comment]
Thank you for your suggestion! I've added the [citation file](https://github.com/GuanLab/DeepSleep/blob/master/CITATION.cff). Let me know if it works or not.

Thanks,
Hongyang

**Comment by Armina1506** [comment]
Thank you very much,  it works very well!
